# Generated by Django 3.0.3 on 2020-07-29 09:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField(blank=True, null=True)),
                ('link1title', models.TextField(blank=True, null=True)),
                ('link1', models.TextField(blank=True, null=True)),
                ('link2title', models.TextField(blank=True, null=True)),
                ('link2', models.TextField(blank=True, null=True)),
                ('link3title', models.TextField(blank=True, null=True)),
                ('link3', models.TextField(blank=True, null=True)),
                ('link4title', models.TextField(blank=True, null=True)),
                ('link4', models.TextField(blank=True, null=True)),
                ('link5title', models.TextField(blank=True, null=True)),
                ('link5', models.TextField(blank=True, null=True)),
                ('monthlyincome', models.IntegerField(blank=True, null=True)),
                ('profitperiod', models.TextField(blank=True, null=True)),
                ('advantage', models.TextField(blank=True, null=True)),
                ('weakness', models.TextField(blank=True, null=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Classifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classification', models.CharField(max_length=10)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Categorys',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=30)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('classification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fmjobs.Classifications')),
            ],
        ),
    ]
