# Generated by Django 3.0.3 on 2020-03-11 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fmjobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='advantage',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='link1',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='link2',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='link3',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='link4',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='link5',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='monthlyincome',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='profitperiod',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='weakness',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(null=True),
        ),
    ]
