# Generated by Django 3.0.3 on 2020-07-29 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fmjobs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorys',
            name='author',
        ),
        migrations.RemoveField(
            model_name='categorys',
            name='published_date',
        ),
        migrations.RemoveField(
            model_name='classifications',
            name='author',
        ),
        migrations.RemoveField(
            model_name='classifications',
            name='published_date',
        ),
    ]
